name: Build
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Install dependencies
        uses: npm ci
      
      - name: Run
        run: |
          npm build
          echo 'cummings.ee' > docs/CNAME

      - name: Commit
        uses: ./.github/actions/commit
        with:
            message: Site build
